services:
  postgresDb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PostgresPW
      POSTGRES_DB: Auctions
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongoDb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=MongoPW
    ports:
      - 27017:27017
    volumes:
      - /data/db
  rabbitMq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672